# -*- coding: utf-8 -*-
"""sea_level_predictor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMYfz1G4oox8W1GJMTMj5jHV7n7zPniZ
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

def draw_plot():
    # Read data from file
    data = pd.read_csv('epa-sea-level.csv')


    # 2 Create scatter plot
    # Use matplotlib to create a scatter plot using the Year column as the x-axis 
    # and the CSIRO Adjusted Sea Level column as the y-axis.
    plt.scatter(data['Year'], data['CSIRO Adjusted Sea Level'])


    # 3 Create first line of best fit
    # Use the linregress function from scipy.stats to get the slope and y-intercept of the line of best fit. 
    # Plot the line of best fit over the top of the scatter plot. 
    # Make the line go through the year 2050 to predict the sea level rise in 2050.
    slope, intercept = linregress(data['Year'], data['CSIRO Adjusted Sea Level'])
    plt.plot(data['Year'], slope*data['Year'] + intercept, color='blue')
    sea_level_2050 = slope*2050 + intercept
    plt.plot(2050, sea_level_2050, color='red', marker='o')


    # 4 Create second line of best fit
    # Plot a new line of best fit just using the data from year 2000 through the most recent year in the dataset. 
    # Make the line also go through the year 2050 to predict the sea level rise in 2050 if the rate of rise 
    # continues as it has since the year 2000.
    data_2000 = data[data['Year'] >= 2000]
    slope, intercept = linregress(data_2000['Year'], data_2000['CSIRO Adjusted Sea Level'])
    plt.plot(data_2000['Year'], slope*data_2000['Year'] + intercept, color='green')
    sea_level_2050_2000 = slope*2050 + intercept
    plt.plot(2050, sea_level_2050_2000, color='green', marker='o')


    # 5 Add labels and title
    # The x label should be Year, the y label should be Sea Level (inches), and the title should be 
    # Rise in Sea Level.
    plt.xlabel('Year')
    plt.ylabel('Sea Level (inches)')
    plt.title('Rise in Sea Level')



    # Save plot and return data for testing (DO NOT MODIFY)
    plt.savefig('sea_level_plot.png')
    return plt.gca()